CREATE TABLE IF NOT EXISTS banco (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  cod_sbif CHAR(3) NOT NULL,
  PRIMARY KEY (id));
  
  INSERT INTO banco (nombre, cod_sbif) VALUES 
('BANCO DE CHILE','001'),
('BANCO INTERNACIONAL', '009'),
('SCOTIABANK CHILE', '014'),
('BANCO DE CREDITO E INVERSIONES', '016'),
('BANCO BICE','028'),
('HSBC BANK (CHILE)', '031'),
('BANCO SANTANDER-CHILE', '037'),
('ITAÚ CORPBANCA', '039'),
('BANCO SECURITY', '049'),
('BANCO FALABELLA', '051'),
('BANCO RIPLEY', '053'),
('RABOBANK CHILE', '054'),
('BANCO CONSORCIO', '055'),
('BANCO PENTA', '056'),
('BANCO BILBAO VIZCAYA ARGENTARIA, CHILE (BBVA)', '504'),
('BANCO BTG PACTUAL CHILE', '059'),
('BANCO DEL ESTADO DE CHILE', '012');
